# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "ugrid.info" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: UGRiD
  avatar: favicon.png
  gravatar: # Email MD5 hash
  description: "UGRiD" # used by search engines

  # Header and footer text
  header_text: >
     <h2>Undergraduate Researchers Interested In Data</h2>

  header_text_feature_image:
  footer_text: >
   <h3>Copyright Â© UGRiD 2016</h3>
   
  # Icons
  rss: false
  email_address:
  behance:
  bitbucket:
  dribbble:
  facebook: "groups/787225494648469"
  flickr:
  github: "tommyjee/ugrid"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/groups/8583903"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-87367917-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
